// <auto-generated />
using BouchonUniversel.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BouchonUniversel.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260718162447_AddChaosSettingsToService")]
    partial class AddChaosSettingsToService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BouchonUniversel.Models.Bouchons.Bouchon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bouchons");
                });

            modelBuilder.Entity("BouchonUniversel.Models.Bouchons.Environnement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Environnement");
                });

            modelBuilder.Entity("BouchonUniversel.Models.Bouchons.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EnvironnementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorProbability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateDates")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironnementId");

                    b.HasIndex("Cle", "EnvironnementId")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BouchonUniversel.Models.SettingsBouchon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingsBouchon");
                });

            modelBuilder.Entity("BouchonUniversel.Models.Bouchons.Service", b =>
                {
                    b.HasOne("BouchonUniversel.Models.Bouchons.Environnement", "Environnement")
                        .WithMany("Services")
                        .HasForeignKey("EnvironnementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environnement");
                });

            modelBuilder.Entity("BouchonUniversel.Models.Bouchons.Environnement", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
